import Nav from './Nav'
import styles from '../styles/Layout.module.css'
import Head from "next/head";

const Layout = ({children}) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav/>
            <div className={styles.container}>
                <main>
                    { children }
                </main>
            </div>
        </>
    )
}

export default Layout